export const Images = {
	NoNet: require('./pngs/no_net.png'),
	eyeShow: require('./pngs/eyeShow.png'),
	eyeHide: require('./pngs/eyeHide.png'),
	closeIcon: require('./pngs/close.png'),
	dotArrowIcon: require('./pngs/dotArrow.png'),
	edit: require('./pngs/edit.png'),
	info: require('./pngs/info.png'),
	logo: require('./pngs/logo.png'),
	right: require('./pngs/right.png'),
	checkUser: require('./pngs/checkUser.png'),
	home: require('./pngs/home.png'),
	attendance: require('./pngs/attendance.png'),
	lead: require('./pngs/lead.png'),
	orders: require('./pngs/orders.png'),
	quotation: require('./pngs/quotation.png'),
	expense: require('./pngs/expense.png'),
	visit: require('./pngs/visit.png'),
	profile: require('./pngs/profile.png'),
	logout: require('./pngs/logout.png'),
	logo_text: require('./pngs/logo_text.png'),
	leftTurn: require('./pngs/leftTurn.png'),
	person: require('./pngs/person.png'),
	phone: require('./pngs/phone.png'),
	clock: require('./pngs/clock.png'),
	happiness: require('./pngs/happiness.png'),
	location: require('./pngs/location.png'),
	plus:require('./pngs/plus.png'),
	search:require('./pngs/search.png'),
	leftArrow:require('./pngs/leftArrow.png'),
	attendanceIImage:require('./pngs/attendanceIImage.png'),
	male_user:require('./pngs/male_user.png'),
	female_user:require('./pngs/female_user.png'),
	userFill:require('./pngs/userFill.png'),
	phoneCall:require('./pngs/phoneCall.png'),
	key:require('./pngs/key.png'),
	downArrow:require('./pngs/downArrow.png'),
	minus:require('./pngs/minus.png'),
	delete:require('./pngs/bin.png'),
	printer:require('./pngs/printer.png'),
	play:require('./pngs/play.png'),
	stop:require('./pngs/stop.png'),
	service:require('./pngs/service.png'),
	notification:require('./pngs/notification.png'),
	add:require('./pngs/add.png'),
	like:require('./pngs/like.png'),
	sun:require('./pngs/sun.png'),
	desLike:require('./pngs/desLike.png'),
	checkmark:require('./pngs/checkmark.png'),
	reject:require('./pngs/reject.png'),
	termsAndConditions:require('./pngs/TermsAndConditions.png'),
	solcon_logo:require('./pngs/solcon_logo.png'),
	whatsapp:require('./pngs/whatsapp.png'),
	edit_icon:require('./pngs/edit_icon.png'),
	notes:require('./pngs/notes.png'),
	more:require('./pngs/more.png'),
	file:require('./pngs/file.png'),
	checkout:require('./pngs/checkout.png'),
	location_mark:require('./pngs/location_mark.png'),
	office:require('./pngs/office.png'),
	leave:require('./pngs/leave.png'),
	report:require('./pngs/report.png'),
	yes:require('./pngs/yes.png'),
	arroba:require('./pngs/arroba.png'),
	identityCard:require('./pngs/identity-card.png'),
	group:require('./pngs/group.png'),
	capture:require('./pngs/capture.png'),
	read_only:require('./pngs/read_only.png'),
};
